// <auto-generated />
using CrudOperationsWithExistingDb.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace CrudOperationsWithExistingDb.Migrations
{
    [DbContext(typeof(SampleCoreDBContext))]
    partial class SampleCoreDBContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("CrudOperationsWithExistingDb.Models.Department", b =>
                {
                    b.Property<int>("PkdepartmentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("PKDepartmentId")
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("DepartmentName")
                        .IsRequired()
                        .HasColumnType("varchar(50)")
                        .HasMaxLength(50)
                        .IsUnicode(false);

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.HasKey("PkdepartmentId");

                    b.ToTable("Department");
                });

            modelBuilder.Entity("CrudOperationsWithExistingDb.Models.Employee", b =>
                {
                    b.Property<int>("PkemployeeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("PKEmployeeId")
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("EmployeeAddress")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("nvarchar(250)")
                        .HasMaxLength(250)
                        .HasDefaultValue("");

                    b.Property<string>("EmployeeName")
                        .IsRequired()
                        .HasColumnType("varchar(50)")
                        .HasMaxLength(50)
                        .IsUnicode(false);

                    b.Property<decimal>("EmployeeSalary")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<int>("FkdeptId")
                        .HasColumnName("FKDeptId")
                        .HasColumnType("int");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.HasKey("PkemployeeId");

                    b.HasIndex("FkdeptId");

                    b.ToTable("Employee");
                });

            modelBuilder.Entity("CrudOperationsWithExistingDb.Models.Employee", b =>
                {
                    b.HasOne("CrudOperationsWithExistingDb.Models.Department", "Fkdept")
                        .WithMany("Employee")
                        .HasForeignKey("FkdeptId")
                        .HasConstraintName("FK_Employee_Department")
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
